### ISSUE TITLE
Add README

### ISSUE THREAD

**Issue by anderspitman** [anderspitman/autobencher#38]

**Comment by lkraider** [comment]
What is autobencher?

**Comment by anderspitman** [comment]
@lkraider Thanks for the inquiry. I added a simple README. Let me know if it's still unclear.

**Comment by lkraider** [comment]
Thank you, it's clear enough for me. I am looking in ways to automate asv, got the link to here from one of the issues where you commented about autobencher.

**Comment by anderspitman** [comment]
Very cool. I'm happy to answer any questions you have if you want to open an issue.
